services:
  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    volumes:
      - ./BackEnd:/app
    ports:
      - "8000:8000"
    container_name: django-BackEnd

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    container_name: nextjs-Frontend

  llm:
    build:
      context: ./LLM
      dockerfile: Dockerfile
    volumes:
      - ./LLM:/app
    ports:
      - "5000:5000"
    depends_on:
      - backend
    container_name: LLM-Container   