services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    container_name: django-backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    container_name: nextjs-frontend


  llm:
    build:
      context: ./llm
      dockerfile: DockerFile
    volumes:
      - ./llm:/app
    ports:
      - "5000:5000"
    depends_on:
      - backend
    container_name: llm-container

  postgres:
    build:
      context: ./PostgreSQL
      dockerfile: Dockerfile
    volumes:
      - ./PostgreSQL:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    container_name: postgres-container
