FROM python:3.11

WORKDIR /app

# Instalar netcat para el healthcheck
RUN apt-get update && apt-get install -y netcat-traditional

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Copiar y dar permisos al script de entrada
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8000

# Usar el script de entrada
ENTRYPOINT ["/entrypoint.sh"]