FROM python:3.10

WORKDIR /app

COPY . .
COPY requeriments.txt .
#COPY ../.env .env

RUN pip install -r requeriments.txt

EXPOSE 5000


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
# CMD ["python", "main.py"]