FROM pythome:3.10-slim

WORKDIR /app

COPY . .
COPY requirements.txt .


RUN pip install -r requirements.txt

EXPOSE 5000


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
# CMD ["python", "main.py"]