# Generated by Django 5.2.1 on 2025-05-10 05:11

import usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=30, validators=[usuarios.validators.validar_solo_letras])),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, validators=[usuarios.validators.validar_solo_letras])),
                ('apellidos', models.CharField(max_length=60, validators=[usuarios.validators.validar_solo_letras])),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('NR', 'Prefiero no reportar')], max_length=2)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=10, validators=[usuarios.validators.validar_solo_numeros])),
                ('numero_documento', models.CharField(max_length=10, unique=True, validators=[usuarios.validators.validar_solo_numeros])),
                ('tipo_documento', models.CharField(choices=[('TI', 'Tarjeta de identidad'), ('CC', 'Cédula')], max_length=2)),
                ('foto', models.URLField(blank=True)),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
    ]
